### ISSUE TITLE
【エラー】UWPBridgeService

### ISSUE THREAD

**Issue by SatoshiRobatoFujimoto** [TakahiroMiyaura/HoloOcrSamples#2]
次のようなエラーが出るのですが、UWPBridgeの参照設定かなにかがいるのでしょうか？
![image](https://cloud.githubusercontent.com/assets/8575789/23917887/3803cd80-0934-11e7-8e1f-5b959a046fab.png)

**Comment by TakahiroMiyaura** [comment]
どのようなプロジェクトの開き方をしたのかがこの情報だけでは何もわからないのですが、
Unityでビルドしていない状態では必要なファイルの大半が生成されていない状態ですのでビルドは通りません。
ReadMe.MDに記載している通り以下の手順で作業をする必要があります。
概要としては以下のような流れになります。

1.Unityでプロジェクトを開き、UWPフォルダに対してビルドを実施する。
2.UWP内のソリューションファイルを開きVisual Studioで開く。

**Comment by SatoshiRobatoFujimoto** [comment]
返信ありがとうございます。
ReadMe.MD通りに行い、ソリューションファイルを開き、デプロイするところでのエラーです。
Unity、VisualStudioともに、再度チェックしてみます。

**Comment by SatoshiRobatoFujimoto** [comment]
既存のUWPフォルダではなく、新しく作るとできました！
ありがとうございました。

**Comment by TakahiroMiyaura** [comment]
連絡ありがとうございます。
念のためこちらで確認してみたのですがgithubから落とした状態から手順通りで正常にビルドできました。
現状原因はわからない状態ではあるのですが、再現ができないので一旦クローズいたします。
