### ISSUE TITLE
Linking Unity camera and media capture

### ISSUE THREAD

**Issue by Narnon** [TakahiroMiyaura/HoloOcrSamples#3]
I'm trying to use your sample in an other project but in the MainPage.xaml.cs there is the DummyElement which is not defined. I looked in the sample project and the problem doesn't occur.
The part in cause is the following :

```
        public async Task SetMediaCapture(MediaCapture capture)
        {
            //Set MediaCapture to CaptureElement.
            DummyElement.Source = capture;

            //Start Preview.
            await capture.StartPreviewAsync();

        }
```
I didn't find a class or anything linked to this DummyElement and I don't know how to declare it or to link it with another object.

I'd be grateful if someone could help me.
Thanks

**Comment by TakahiroMiyaura** [comment]
Dear Narnon,

DummyElement is CaptureElemnt Class.
It’s define with Xaml element in MainPage.xaml

please check [MainPage.xaml](https://github.com/TakahiroMiyaura/HoloOcrSamples/blob/master/UWP/HoloOcrSamples/MainPage.xaml) .

If you will create new another project , please try edit MainPage.xaml by using [repository](https://github.com/TakahiroMiyaura/HoloOcrSamples/blob/master/UWP/HoloOcrSamples/MainPage.xaml) as reference.

**Comment by Narnon** [comment]
Dear Takahiro Miyaura,

It worked well.
Thank you very much for your help and your quick answer.
